### ISSUE TITLE
Llista de tipus de via desactualitzat

### ISSUE THREAD

**Issue by GuillemDistricte** [ConsorciAOC/Hestia#1]
Falten tipus de via a la llista, en surten 34 i Hèstia m'està retornant el 36

**Comment by albciff** [comment]
Sembla que ja està actualitzat: https://github.com/ConsorciAOC/Hestia/commit/1b47299571d65bca798ee69ed622c886ea19c9ab#diff-a5cc9d3672f71bfe33a4e9968b8ed8958f314bf69d77a18e7e7eed924785f537
